package DAL;
// Generated 3-dec-2014 15:53:26 by Hibernate Tools 3.6.0



/**
 * Docent generated by hbm2java
 */
public class Docent  implements java.io.Serializable {


     private Integer id;
     private String naam;
     private String email;
     private String gsmNummer;
     private String adres;
     private String richting;

    public Docent() {
    }

    public Docent(String naam, String email, String gsmNummer, String adres, String richting) {
       this.naam = naam;
       this.email = email;
       this.gsmNummer = gsmNummer;
       this.adres = adres;
       this.richting = richting;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getGsmNummer() {
        return this.gsmNummer;
    }
    
    public void setGsmNummer(String gsmNummer) {
        this.gsmNummer = gsmNummer;
    }
    public String getAdres() {
        return this.adres;
    }
    
    public void setAdres(String adres) {
        this.adres = adres;
    }
    public String getRichting() {
        return this.richting;
    }
    
    public void setRichting(String richting) {
        this.richting = richting;
    }




}


