package DAL;
// Generated 3-dec-2014 15:53:26 by Hibernate Tools 3.6.0



/**
 * Lokaal generated by hbm2java
 */
public class Lokaal  implements java.io.Serializable {


     private Integer id;
     private String lokaalNummer;
     private int zitplaatsen;
     private boolean beschikbaar;

    public Lokaal() {
    }

    public Lokaal(String lokaalNummer, int zitplaatsen, boolean beschikbaar) {
       this.lokaalNummer = lokaalNummer;
       this.zitplaatsen = zitplaatsen;
       this.beschikbaar = beschikbaar;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLokaalNummer() {
        return this.lokaalNummer;
    }
    
    public void setLokaalNummer(String lokaalNummer) {
        this.lokaalNummer = lokaalNummer;
    }
    public int getZitplaatsen() {
        return this.zitplaatsen;
    }
    
    public void setZitplaatsen(int zitplaatsen) {
        this.zitplaatsen = zitplaatsen;
    }
    public boolean isBeschikbaar() {
        return this.beschikbaar;
    }
    
    public void setBeschikbaar(boolean beschikbaar) {
        this.beschikbaar = beschikbaar;
    }




}


